# Generated by Django 3.0.5 on 2020-04-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=10)),
                ('appointment_date', models.CharField(max_length=100)),
                ('appointment_time', models.TimeField()),
                ('assign_branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('services', models.CharField(max_length=100)),
                ('opening_date', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_price', models.IntegerField()),
                ('service_tax', models.FloatField()),
                ('discount', models.FloatField()),
                ('serivice_img', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('joining_date', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('staff_img', models.ImageField(upload_to='img/')),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('shift', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salon_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_img', models.ImageField(upload_to='img/')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salon_img', to='appointment.Salon')),
            ],
        ),
    ]
