# Generated by Django 3.0.5 on 2020-04-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='assign_branch',
            new_name='assign_staff',
        ),
    ]
