# Generated by Django 3.0.5 on 2020-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200429_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='location',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='location',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='staff',
            name='shift',
            field=models.CharField(max_length=100),
        ),
    ]
