# Generated by Django 3.0.5 on 2020-04-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_salon_manager_salon_receptionist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salon_Manager',
        ),
        migrations.DeleteModel(
            name='Salon_Receptionist',
        ),
    ]
