# Generated by Django 3.0.5 on 2020-04-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_salon_manager_salon_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salon',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appointment.Salon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='salon_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
