# Generated by Django 3.0.5 on 2020-04-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_remove_staff_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon_manager',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment.Salon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon_receptionist',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment.Salon'),
            preserve_default=False,
        ),
    ]
