# Generated by Django 3.0.5 on 2020-05-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20200504_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
    ]
