# Generated by Django 3.0.5 on 2020-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_remove_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
