# Generated by Django 3.0.5 on 2020-04-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200430_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='topup',
            field=models.IntegerField(default=0),
        ),
    ]
